apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
      - name: monitoring-app
        image: gcr.io/monitoring-app-460407/monitoring-app
        ports:
        - containerPort: 3000
